SystemZarzadzaniaSchroniskiem/Controllers/BugReportsController.cs
using SystemZarzadzaniaSchroniskiem.Models;
using SystemZarzadzaniaSchroniskiem.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SystemZarzadzaniaSchroniskiem.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity.UI.Services;
using System.Threading.Tasks;
using System.Net.WebSockets;

namespace SystemZarzadzaniaSchroniskiem.Controllers
{
    [Authorize]
    public class BugReportsController : SchroniskoController
    {
        public delegate void BugReportEventHandler(object sender, BugReportEventArgs e);

        public event BugReportEventHandler BugReportCreated;
        public event BugReportEventHandler BugReportCommentCreated;

        private readonly BugReportService _bugReportService;

        public BugReportsController(
            SchroniskoDbContext context,
            IWebHostEnvironment env,
            UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager,
            IUserStore<IdentityUser> userStore,
            IEmailSender sender,
            ILogger<SchroniskoController> logger,
            BugReportService bugReportService) : base(
                context, env, userManager, signInManager, userStore, sender, logger)
        {
            _bugReportService = bugReportService;
            BugReportCreated += _bugReportService.OnBugReportCreated;
            BugReportCommentCreated += _bugReportService.OnBugReportCommentCreated;
        }

        public async Task<IActionResult> Index()
        {
            List<BugReport> reports;

            if (HttpContext.Items["UserProfile"] is not UserProfile profile)
            {
                return Forbid();
            }

            bool isAdmin = await _userManager.IsInRoleAsync(profile.User, "Administrator");

            if (isAdmin)
            {
                reports = await _dbContext.BugReports.Include(br => br.Profile).ThenInclude(p => p.User).ToListAsync();
            }
            else
            {
                reports = await _dbContext.BugReports.Where(r => r.ProfileId == profile.Id).ToListAsync();
            }

            return View(reports);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (HttpContext.Items["UserProfile"] is not UserProfile profile)
            {
                return Forbid();
            }

            var report = _dbContext.BugReports
                .Include(br => br.Profile)
                .ThenInclude(p => p.User)
                .Include(br => br.Comments)
                .FirstOrDefault(br => br.Id == id);

            if (report == null)
            {
                return NotFound();
            }

            var isAdmin = await _userManager.IsInRoleAsync(profile.User, "Administrator");

            if (!isAdmin && report.Profile != profile)
            {
                return Forbid();
            }

            return View(report);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> ChangeStatus(int BugReportId, BugReportStatus Status)
        {
            var report = await _dbContext.BugReports.SingleOrDefaultAsync(br => br.Id == BugReportId);
            if (report == null)
            {
                return NotFound();
            }

            report.Status = Status;

            await _dbContext.SaveChangesAsync();

            return RedirectToAction("Details", new { Id = report.Id });
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateComment([Bind("Content,BugReportId")] BugReportComment comment)
        {
            if (HttpContext.Items["UserProfile"] is not UserProfile profile)
            {
                return Forbid();
            }
            comment.DateCreated = DateTime.Now;
            comment.ProfileId = profile.Id;
            _dbContext.Add(comment);
            await _dbContext.SaveChangesAsync();
            BugReportCommentCreated?.Invoke(this, new BugReportEventArgs { Comment = comment });

            return RedirectToAction("Details", new { Id = comment.BugReportId });
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Description")] BugReport report)
        {
            if (HttpContext.Items["UserProfile"] is not UserProfile profile)
            {
                return Forbid();
            }
            report.DateCreated = DateTime.Now;
            report.Status = BugReportStatus.Open;
            report.ProfileId = profile.Id;
            _dbContext.Add(report);
            await _dbContext.SaveChangesAsync();
            BugReportCreated?.Invoke(this, new BugReportEventArgs { Report = report });
            return RedirectToAction("Details", new { Id = report.Id });
        }
    }
}

SystemZarzadzaniaSchroniskiem/Views/Shared/Navbar.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


@{
	bool isAdmin = User.IsInRole("Administrator");
	bool isEmployee = User.IsInRole("Employee");
	bool isVet = User.IsInRole("Veterinarian");
	bool isVolunteer = User.IsInRole("Volunteer");
	bool hasMenuAccess = isAdmin || isEmployee || isVet || isVolunteer;
}


<style>
	#navbar .nav-link {
		color: var(--sc-lightblue);
		text-decoration: none;
		display: flex;
		align-items: center;
		gap: 6px;
	}

	#navbar .dropdown-menu {
		background-color: var(--sc-orange-50);
		backdrop-filter: blur(5px);
	}

	#navbar .dropdown-item {
		display: flex;
		gap: 10px;
		align-items: center;
	}

	#navbar .dropdown-item:hover {
		background-color: var(--sc-beige-80);
	}
</style>

<nav class="navbar navbar-expand-md navbar-toggleable-md" id="navbar">
	<div class="container-fluid">
		<a id="navbar-brand" asp-controller="Home" asp-action="Index"
			style="color: var(--sc-beige); text-decoration: none; margin-right: 20px;">
			<div class="d-flex align-items-center gap-2">
				<i class="fas fa-shield-dog"></i> Schronisko
			</div>
		</a>


		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
			aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="navbar-collapse collapse d-md-inline-flex justify-content-between">
			<ul class="navbar-nav flex-grow-1 gap-4">

				<li class="nav-item">
					<a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
						<i class="bi bi-house-door"></i>
						Home
					</a>
				</li>

				<li class="nav-item">
					<a class="nav-link" asp-controller="Pets" asp-action="Index">
						<i class="fas fa-paw"></i>

						Zwierzaki
					</a>
				</li>

				<li class="nav-item">
					<a class="nav-link" asp-controller="Events" asp-action="Index">
						<i class="bi bi-calendar2-week"></i>
						Wydarzenia
					</a>
				</li>


				@if (hasMenuAccess)
				{
					<li class="nav-item dropdown">

						<a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							<i class="bi bi-shield"></i>
							Administracja
						</a>

						<ul class="dropdown-menu">
							@if (isAdmin || isEmployee || isVolunteer || isVet)
							{
								<a asp-controller="Pets" asp-action="Database" class="dropdown-item">
									@* <i class="fas fa-paw"></i> *@
									<icon name="fa-paw" />
									Zwierzęta
								</a>
							}

							@if (isAdmin)
							{
								<a asp-controller="Pets" asp-action="Breeds" class="dropdown-item">
									<i class="fas fa-dragon"></i>
									Rasy
								</a>

								<a asp-controller="UserProfiles" asp-action="Index" class="dropdown-item">
									<i class="fas fa-user"></i>
									Użytkownicy
								</a>
							}

							@if (isAdmin || isEmployee || isVolunteer)
							{
								<a asp-controller="Events" asp-action="Database" class="dropdown-item">
									<i class="bi bi-calendar2-week"></i>
									Wydarzenia
								</a>
							}

							@if (isAdmin)
							{
								<a asp-controller="Appointments" asp-action="Database" class="dropdown-item">
									<i class="fas fa-calendar-check"></i>
									Wizyty
								</a>
							}

							@if (isAdmin)
							{
								<li class="dropdown-divider"></li>

								<a asp-area="" asp-controller="BugReports" asp-action="Index" class="dropdown-item">
									<i class="bi bi-bug"></i> Zgłoszenia Błędów
								</a>
							}
						</ul>
					</li>
				}
			</ul>
			<partial name="_LoginPartial" />
		</div>
	</div>
</nav>

SystemZarzadzaniaSchroniskiem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Schronisko</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/lib/bootstrap-icons/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/regular.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/solid.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/all.min.css" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/forms.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SystemZarzadzaniaSchroniskiem.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)
    <style>
        .nav-link {
            border-bottom: 2px solid transparent;
        }

        .nav-link:hover,
        .nav-link:active {
            border-bottom: 2px solid var(--sc-orange-80) !important;
            color: var(--sc-orange) !important;
            using Microsoft.AspNetCore.Razor.Language.Intermediate;

            #line default #line hidden #nullable disable ullable disable
        }

        #messages {
            position: fixed;
            top: 0;
            left: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            width: 100%;
            margin: -20px;
            margin-top: 80px;
        }

        .view-message {
            background-color: #fff8;
            backdrop-filter: blur(4px);
            transition: opacity 0.4s;
            width: 80vw;
        }

        .view-message .btn-close {
            background-color: #fff8;
        }

        .view-message:hover {
            opacity: 1;
        }

        .view-message-Primary {
            background-color: var(--sc-navy-80);
            color: var(--sc-white-80);
        }

        .view-message-Primary .toast-header {
            color: var(--sc-lightblue);
        }

        .view-message-Success {
            background-color: var(--sc-green-80);
            color: var(--sc-white-80);
        }

        .view-message-Success .toast-header {
            color: var(--sc-white-60);
        }

        .view-message-Danger {
            background-color: var(--sc-red-80);
        }

        .view-message-Danger .toast-header {
            color: var(--sc-white-80);
        }

        .view-message-Alert {
            background-color: var(--sc-yellow-80);
        }

        .view-message-Alert .toast-header {
            color: var(--sc-white-80);
        }

        #debug {
            position: fixed;
            top: 60px;
            left: 0;
            background-color: #0002;
            color: white;
            z-index: 100;
            padding: 4px;
            font-family: monospace;
            font-size: 12px;
        }

        #debug:hover {
            background-color: #000f;

        }
    </style>

</head>


<body>
    @* <div id="debug">
        <div>xs: 0</div>
        <div>sm: 576px</div>
        <div>md: 768px</div>
        <div>lg: 992px</div>
        <div>xl: 1200px</div>
        <div>xxl: 1400px</div>
    </div> *@
    <header>
        <partial name="Navbar" />
    </header>

    <main role="main" style="min-height: 88vh; padding: 50px 0;">
        @RenderBody()
        @if (TempData["ViewMessage"] != null)
        {
            var messageType = TempData["ViewMessageType"] ?? "primary";

            <div id="messages" class="toast-container">
                <div class="toast view-message view-message-@messageType show" role="alert" aria-live="assertive"
                    data-bs-autohide="false" aria-atomic="true">
                    <div class="toast-header" style="background-color: rgba(0,0,0,0.25); backdrop-filter: blur(4px);">
                        <strong class="me-auto">
                            @TempData["ViewMessageTitle"]
                        </strong>
                        @* <small>11 mins ago</small> *@
                        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                    </div>
                    <div class="toast-body">
                        @TempData["ViewMessage"]
                    </div>
                </div>
            </div>
        }
    </main>

    <footer class="border-top footer p-4" style="background-color: var(--sc-orange-80);">
        <div class="container">
            &copy; 2025 - Schronisko -
            <a asp-controller="Home" asp-action="Privacy" class="link-secondary">Polityka prywatności</a>
            @if (!User.IsInRole("Administrator"))
            {
                <span>-</span>
                <a asp-area="" asp-controller="BugReports" asp-action="Create" class="link-secondary">Zgłoś Błąd</a>
            }
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>


</html>